/* ------------------------------------------------------------------ */
/*  Centralized keyword database for visaprocessinfo.com               */
/*  ~100+ keywords per page category for maximum organic reach         */
/* ------------------------------------------------------------------ */

export const HOMEPAGE_KEYWORDS: string[] = [
  "visa guide","immigration guide","visa application","visa requirements 2026","study visa","work visa",
  "tourist visa","permanent residency","visa process","visa fees","visa interview","visa appointment",
  "immigration process","visa checklist","visa documents","passport visa","embassy appointment",
  "visa application form","visa approval","visa rejection","visa appeal","visa consultant",
  "visa tracker","visa status","e-visa","visa on arrival","transit visa","business visa",
  "investor visa","golden visa","digital nomad visa","freelance visa","family visa","spouse visa",
  "dependent visa","visa extension","visa renewal","visa cancellation","visa transfer",
  "immigration lawyer","immigration consultant","visa agency","visa processing time",
  "visa application online","biometric appointment","visa photo requirements","visa fee payment",
  "travel insurance visa","bank statement visa","cover letter visa","invitation letter visa",
  "visa from Pakistan","visa from India","visa from Nigeria","visa from Bangladesh",
  "how to apply for visa","visa tips","visa success rate","visa refusal reasons",
  "Schengen visa","US visa","UK visa","Canada visa","Australia visa","Germany visa",
  "UAE visa","Turkey visa","Saudi Arabia visa","Italy visa","France visa","Spain visa",
  "Netherlands visa","Sweden visa","Norway visa","Switzerland visa","visa 2026",
  "immigration 2026","study abroad 2026","work abroad 2026","travel visa 2026",
  "visa guide online","free visa guide","visa help","visa information","visa advice",
  "embassy visa","consulate visa","visa application center","VFS Global","TLS Contact",
  "visa slot booking","visa appointment booking","visa interview questions",
  "visa medical examination","police clearance certificate","visa financial requirements",
  "proof of funds visa","accommodation proof visa","return ticket visa",
  "visa application deadline","visa processing delay","expedited visa processing",
  "urgent visa application","visa waiver","visa exemption","visa free countries",
  "strongest passport","passport ranking 2026","dual citizenship","second passport",
  "citizenship by investment","residency by investment","points based immigration",
  "express entry","skilled worker visa","employer sponsored visa","post study work visa",
  "graduate visa","student permit","work permit","residence permit","settlement visa",
  "indefinite leave to remain","green card","H1B visa","F1 visa","visaprocessinfo",
];

export function generateCountryKeywords(countryName: string, slug: string): string[] {
  const base = [
    `${countryName} visa`,`${countryName} visa guide`,`${countryName} visa requirements`,
    `${countryName} visa 2026`,`${countryName} study visa`,`${countryName} work visa`,
    `${countryName} tourist visa`,`${countryName} visitor visa`,`${countryName} immigration`,
    `${countryName} permanent residency`,`${countryName} PR`,`${countryName} visa fees`,
    `${countryName} visa processing time`,`${countryName} visa application`,
    `${countryName} visa documents`,`${countryName} visa checklist`,
    `${countryName} visa interview`,`${countryName} visa appointment`,
    `${countryName} embassy`,`${countryName} consulate`,`${countryName} visa online`,
    `${countryName} e-visa`,`${countryName} visa from Pakistan`,
    `${countryName} visa from India`,`${countryName} visa from Nigeria`,
    `${countryName} student visa`,`${countryName} work permit`,
    `${countryName} business visa`,`${countryName} investor visa`,
    `${countryName} family visa`,`${countryName} spouse visa`,
    `${countryName} dependent visa`,`${countryName} visa rejection`,
    `${countryName} visa appeal`,`${countryName} visa success rate`,
    `${countryName} visa tips`,`how to apply ${countryName} visa`,
    `${countryName} visa step by step`,`${countryName} visa process`,
    `${countryName} visa cost`,`${countryName} visa duration`,
    `${countryName} visa validity`,`${countryName} visa extension`,
    `${countryName} visa requirements for Pakistani`,
    `${countryName} visa requirements for Indian`,
    `study in ${countryName}`,`work in ${countryName}`,`visit ${countryName}`,
    `immigrate to ${countryName}`,`settle in ${countryName}`,
    `${countryName} scholarship`,`${countryName} university admission`,
    `${countryName} job visa`,`${countryName} skilled worker visa`,
    `${countryName} points system`,`${countryName} citizenship`,
    `${countryName} passport`,`${countryName} residency`,
    `${countryName} immigration 2026`,`${countryName} visa update`,
    `${countryName} new visa rules`,`${countryName} visa policy`,
    `${countryName} cost of living`,`${countryName} salary`,
    `${countryName} job market`,`${countryName} best universities`,
    `${countryName} visa biometrics`,`${countryName} visa photo`,
    `${countryName} visa bank statement`,`${countryName} visa financial proof`,
    `${countryName} visa cover letter`,`${countryName} visa travel insurance`,
    `${countryName} visa medical exam`,`${countryName} police clearance`,
    `${countryName} accommodation proof`,`${countryName} visa invitation letter`,
    `${countryName} visa processing delay`,`${countryName} visa fast track`,
    `${countryName} visa refusal reasons`,`${countryName} visa consultant`,
    `${countryName} immigration lawyer`,`${countryName} VFS appointment`,
    `${countryName} embassy appointment`,`${countryName} visa slot`,
    `${countryName} visa tracker`,`${countryName} visa status check`,
    `${slug} visa`,`${slug} visa guide`,`${slug} visa 2026`,
    `${slug} immigration`,`${slug} study visa`,`${slug} work permit`,
  ];
  return [...new Set(base)];
}

export const VISA_TYPE_KEYWORDS: Record<string, string[]> = {
  study: [
    "study visa","student visa","study abroad","international student","university visa",
    "college visa","student permit","study permit","F1 visa","Tier 4 visa","subclass 500",
    "study visa requirements","study visa fees","study visa processing time",
    "study visa documents","study visa checklist","study visa interview",
    "study visa from Pakistan","study visa from India","study visa from Nigeria",
    "how to apply study visa","study visa step by step","study visa 2026",
    "study visa application","study visa online","study visa appointment",
    "scholarship visa","tuition fee visa","student accommodation",
    "post study work visa","post graduation work permit","PGWP","graduate route",
    "OPT visa","CPT visa","student work rights","part time work student visa",
    "study visa bank statement","study visa financial proof","study visa SOP",
    "statement of purpose","study plan visa","admission letter visa",
    "conditional offer letter","unconditional offer","CAS letter","I-20 form",
    "CoE confirmation of enrollment","study visa IELTS","study visa TOEFL",
    "study visa PTE","English test visa","language requirements student visa",
    "study visa medical exam","study visa health insurance","OSHC","UHIC",
    "study visa cover letter","study visa motivation letter",
    "best countries study abroad 2026","cheapest countries study abroad",
    "study visa success tips","study visa rejection reasons",
    "study visa appeal","study visa reapplication","study visa extension",
    "study visa to work visa","student to PR pathway","study visa scholarship",
    "fully funded scholarship 2026","study in USA","study in UK","study in Canada",
    "study in Australia","study in Germany","study abroad free","tuition free universities",
    "study visa consultant","education agent","study abroad guide",
    "study visa processing delay","study visa biometrics","campus France",
    "DAAD scholarship","Chevening scholarship","Commonwealth scholarship",
    "Fulbright scholarship","study visa spouse","student dependent visa",
    "study visa timeline","study visa approval rate","study visa trends 2026",
    "study visa news","study visa policy update","study visa new rules",
    "study visa age limit","study visa gap year","study visa work experience",
    "MBA visa","PhD visa","masters visa","undergraduate visa","diploma visa",
    "vocational training visa","language course visa","exchange student visa",
  ],
  work: [
    "work visa","work permit","skilled worker visa","employer sponsored visa",
    "H1B visa","H2B visa","L1 visa","TN visa","E2 visa","O1 visa",
    "UK skilled worker visa","Canada work permit","LMIA","Australia TSS visa",
    "subclass 482","EU Blue Card","Germany work visa","ICT visa",
    "intra company transfer","work visa requirements","work visa fees",
    "work visa processing time","work visa documents","work visa checklist",
    "work visa interview","work visa from Pakistan","work visa from India",
    "how to get work visa","work visa 2026","work visa application",
    "work permit application","job offer visa","employer sponsorship",
    "labor market test","skills assessment","credential evaluation",
    "work visa to PR","work visa to permanent residency","work visa extension",
    "work visa renewal","work visa transfer","change employer visa",
    "work visa salary threshold","minimum salary visa","work visa points",
    "express entry","CRS score","skilled occupation list","SOL","PMSOL",
    "critical skills list","shortage occupation list","IELTS work visa",
    "work visa English requirement","work visa experience requirement",
    "work visa age limit","work visa health check","work visa police clearance",
    "work visa dependent","work visa family","work visa spouse","work visa children",
    "remote work visa","digital nomad visa","freelance visa","self employed visa",
    "startup visa","entrepreneur visa","investor visa","business visa work",
    "seasonal worker visa","temporary work visa","permanent work visa",
    "work abroad 2026","jobs abroad","international jobs","overseas employment",
    "work visa consultant","immigration lawyer work visa","work visa agency",
    "work visa success tips","work visa rejection reasons","work visa appeal",
    "highest paying countries","best countries work abroad",
    "work visa processing delay","work visa fast track","priority visa",
    "work visa news 2026","work visa policy update","new work visa rules",
    "tech visa","healthcare visa","nursing visa","engineering visa","IT visa",
    "teaching visa","chef visa","construction visa","agriculture visa",
  ],
  tourist: [
    "tourist visa","visitor visa","travel visa","Schengen visa","B1 B2 visa",
    "eTA Canada","ETA Australia","e-visa","visa on arrival","tourist visa requirements",
    "tourist visa fees","tourist visa processing time","tourist visa documents",
    "tourist visa checklist","tourist visa interview","tourist visa application",
    "tourist visa online","tourist visa from Pakistan","tourist visa from India",
    "how to apply tourist visa","tourist visa 2026","tourist visa step by step",
    "Schengen visa application","Schengen visa requirements","Schengen visa fees",
    "Schengen visa from Pakistan","Schengen visa from India","Schengen visa countries",
    "tourist visa bank statement","tourist visa financial proof","tourist visa itinerary",
    "tourist visa hotel booking","tourist visa flight ticket","tourist visa insurance",
    "travel insurance Schengen","tourist visa cover letter","tourist visa invitation letter",
    "tourist visa sponsor","tourist visa host","tourist visa accommodation proof",
    "tourist visa photo","tourist visa biometrics","tourist visa appointment",
    "VFS tourist visa","TLS Contact tourist visa","tourist visa slot booking",
    "tourist visa rejection","tourist visa refusal","tourist visa appeal",
    "tourist visa reapply","tourist visa success tips","tourist visa tips",
    "tourist visa duration","tourist visa validity","tourist visa extension",
    "tourist visa multiple entry","tourist visa single entry","transit visa",
    "airport transit visa","layover visa","stopover visa",
    "visa free countries 2026","visa on arrival countries","e-visa countries",
    "best countries to visit 2026","cheapest tourist visa","easiest tourist visa",
    "fastest tourist visa","same day visa","urgent tourist visa",
    "family visit visa","friend visit visa","medical visa","treatment visa",
    "pilgrimage visa","Hajj visa","Umrah visa","tourist to student visa",
    "tourist to work visa","overstay visa","visa violation","visa ban",
    "travel visa consultant","visa agency tourist","tourist visa guide",
    "tourist visa processing delay","tourist visa news 2026",
    "UAE tourist visa","Turkey e-visa","Saudi tourist visa","Japan tourist visa",
    "USA tourist visa B2","UK visitor visa","Canada visitor visa",
    "Australia visitor visa","Europe tourist visa","Dubai visa",
  ],
  immigration: [
    "permanent residency","PR visa","green card","settlement visa","ILR",
    "indefinite leave to remain","permanent residence","citizenship",
    "naturalization","immigration","immigration guide","immigration 2026",
    "PR application","PR requirements","PR processing time","PR fees",
    "PR points","PR score","express entry","CRS score","CRS calculator",
    "provincial nominee program","PNP","state nomination","skilled migration",
    "family sponsorship","spouse sponsorship","parent sponsorship",
    "PR from study visa","PR from work visa","PR pathway","PR timeline",
    "Canada PR","Australia PR","UK settlement","Germany settlement permit",
    "USA green card","green card lottery","DV lottery","EB5 visa",
    "investor immigration","business immigration","entrepreneur immigration",
    "self employed immigration","retirement visa","retiree visa",
    "family immigration","family reunification","family visa PR",
    "citizenship test","citizenship ceremony","citizenship requirements",
    "dual citizenship","second citizenship","citizenship by investment",
    "citizenship by descent","citizenship by marriage","citizenship timeline",
    "PR to citizenship","how long PR to citizenship","citizenship fees",
    "immigration lawyer","immigration consultant","RCIC","MARA agent",
    "immigration points calculator","immigration eligibility check",
    "immigration medical exam","immigration police clearance",
    "immigration English test","immigration IELTS","immigration language",
    "immigration financial requirements","immigration proof of funds",
    "immigration application form","immigration documents checklist",
    "immigration interview","immigration biometrics",
    "fastest PR countries","easiest PR countries","best countries immigration",
    "cheapest PR countries","PR success rate","PR rejection reasons",
    "PR appeal","PR reapplication","PR extension","PR renewal",
    "PR rights","PR benefits","PR vs citizenship","PR travel rights",
    "immigration news 2026","immigration policy update","new immigration rules",
    "immigration reform","immigration trends","immigration statistics",
    "skilled worker immigration","healthcare worker immigration",
    "tech worker immigration","trade worker immigration",
    "age limit immigration","immigration age points","immigration work experience",
    "immigration education points","immigration qualification assessment",
    "WES evaluation","NARIC evaluation","skills assessment immigration",
  ],
  business: [
    "business visa","business travel visa","corporate visa","conference visa",
    "business visitor visa","B1 visa","business e-visa","business visa requirements",
    "business visa fees","business visa processing time","business visa documents",
    "business visa application","business visa online","business visa 2026",
    "business visa from Pakistan","business visa from India",
    "how to apply business visa","business visa step by step",
    "business invitation letter","business visa cover letter",
    "business meeting visa","trade fair visa","exhibition visa",
    "investor visa","golden visa","startup visa","entrepreneur visa",
    "business immigration","company registration visa","branch office visa",
    "UAE golden visa","UAE investor visa","Turkey investor visa",
    "UK innovator founder visa","Canada startup visa","US E2 treaty investor",
    "Portugal golden visa","Spain investor visa","Netherlands startup visa",
    "business visa bank statement","business visa financial proof",
    "business visa company documents","business visa registration",
    "business visa trade license","business visa tax returns",
    "business visa duration","business visa validity","business visa extension",
    "business visa multiple entry","business visa single entry",
    "business visa to work visa","business visa to PR",
    "franchise visa","self employed visa","freelancer visa business",
    "digital nomad business","remote business visa","international business visa",
    "export import visa","trade visa","commercial visa",
    "business visa rejection","business visa refusal","business visa appeal",
    "business visa success tips","business visa consultant",
    "best countries business visa","easiest business visa",
    "business visa processing delay","business visa fast track",
    "business visa news 2026","business visa policy update",
    "company sponsor visa","corporate transfer visa","executive visa",
    "board meeting visa","shareholder visa","director visa",
    "business visa interview questions","business visa appointment",
    "business visa biometrics","business visa photo requirements",
    "APEC business travel card","global entry","trusted traveler",
    "business visa insurance","business travel insurance",
    "multi country business visa","Schengen business visa",
  ],
};

export const BLOG_KEYWORDS: string[] = [
  "visa blog","immigration blog","visa articles","visa guides","visa tips",
  "visa news","immigration news","visa updates 2026","visa policy changes",
  "how to apply for visa","visa application tips","visa interview tips",
  "visa document preparation","visa checklist guide","visa fee guide",
  "visa processing time guide","visa success stories","visa rejection stories",
  "study visa guide","work visa guide","tourist visa guide","PR guide",
  "business visa guide","investor visa guide","digital nomad guide",
  "country visa guide","visa comparison","best visa options",
  "visa for beginners","first time visa application","visa FAQ",
  "visa questions answers","visa myths","visa facts","visa mistakes",
  "common visa errors","visa do and donts","visa preparation guide",
  "visa appointment guide","biometric guide","visa photo guide",
  "bank statement guide","financial proof guide","cover letter guide",
  "SOP guide","motivation letter guide","invitation letter guide",
  "travel insurance guide","medical exam guide","police clearance guide",
  "visa from Pakistan guide","visa from India guide","visa from Nigeria guide",
  "study abroad blog","work abroad blog","travel blog visa",
  "immigration blog 2026","visa blog 2026","latest visa news",
  "visa policy update","new visa rules","visa changes 2026",
  "embassy news","consulate updates","visa processing updates",
  "visa slot availability","visa appointment availability",
  "visa success rate","visa approval tips","visa strategy",
  "immigration pathway","PR pathway guide","citizenship guide",
  "dual citizenship guide","second passport guide",
  "points calculator guide","CRS score guide","express entry guide",
  "skilled worker guide","employer sponsorship guide",
  "post study work guide","graduate route guide","PGWP guide",
  "scholarship guide","tuition guide","cost of living guide",
  "salary comparison guide","job market guide","best countries guide",
  "easiest visa countries","fastest visa processing","cheapest visa",
  "visa free travel","visa on arrival guide","e-visa guide",
  "Schengen visa guide","US visa guide","UK visa guide","Canada visa guide",
  "Australia visa guide","Germany visa guide","UAE visa guide",
  "visa consultant review","immigration lawyer guide",
  "visa application online guide","visa form filling guide",
  "visa tracking guide","visa status check guide",
];

export const PROCESS_KEYWORDS: string[] = [
  "visa application process","how to apply for visa","visa step by step",
  "visa application guide","visa process 2026","visa procedure",
  "embassy application process","consulate visa process","online visa application",
  "visa form filling","visa submission","visa appointment process",
  "biometric process","visa photo process","document submission process",
  "visa fee payment process","visa tracking process","visa collection process",
  "visa interview process","visa approval process","visa decision process",
  "study visa process","work visa process","tourist visa process","PR process",
  "business visa process","investor visa process","family visa process",
  "spouse visa process","dependent visa process","transit visa process",
  "e-visa process","visa on arrival process","visa extension process",
  "visa renewal process","visa transfer process","visa appeal process",
  "visa reapplication process","document preparation","document checklist",
  "application timeline","processing timeline","visa timeline",
  "step 1 visa application","gather documents visa","submit application visa",
  "attend interview visa","wait for decision visa","collect visa passport",
  "visa application mistakes","common errors visa application",
  "tips visa application","visa application strategy",
  "first time applicant guide","visa application for beginners",
  "visa application requirements","eligibility check visa",
  "visa application fees breakdown","visa service charge",
  "VFS application process","TLS Contact process","embassy direct application",
  "online portal visa","visa application portal","immigration portal",
  "visa application center","visa office","immigration office",
  "visa processing time breakdown","standard processing","priority processing",
  "super priority visa","expedited processing","fast track visa",
  "visa application preparation","pre application checklist",
  "post application steps","after visa approval","after visa rejection",
  "visa stamping process","visa endorsement","entry clearance process",
  "landing process","port of entry","immigration at airport",
  "visa validity check","visa conditions","visa restrictions",
  "visa compliance","visa terms","visa obligations",
  "application form guide","DS-160 guide","UK visa form guide",
  "Canada application form","Australia ImmiAccount","Germany visa form",
  "UAE visa application","Turkey e-visa application","Saudi visa application",
  "Schengen application form","visa application checklist PDF",
  "printable visa checklist","visa document organizer",
  "visa application tracker","visa status checker","visa decision notification",
];

export function mergeKeywords(...arrays: string[][]): string[] {
  return [...new Set(arrays.flat())];
}
